
POST http://localhost:3700/users/login 
Content-Type: application/json

{
  "nickname":"guest",
  "password":"12345678"
}

###
GET http://localhost:3700/jwt
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5pY2tuYW1lIjoiZ3Vlc3QiLCJpYXQiOjE2NjAzNTkyNTcsImV4cCI6MTY2Mjk1MTI1N30.bsjk_rdDMexKtRHzc7IW5rFyF0FToMVXpco5ed0XP9g


###
GET http://localhost:3700/tryThis
Authorization: Bearer eaaaayJhbGciOiJasdIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5pY2tuYW1lIjoiZ3Vlc3QiLCJpYXQiOjE2NjA4Nzk3ODYsImV4cCI6MTY2MzQ3MTc4Nn0.h3XVwDZBTgeOAByX8zBfb8k_mGjBXFynOa-VBw5QcsI