
POST http://localhost:3700/users/login 
Content-Type: application/json

{
  "nickname":"guest",
  "password":"12345678"
}

###
GET http://localhost:3700/users/get-posts-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5pY2tuYW1lIjoiZ3Vlc3QiLCJpYXQiOjE2NjA5NjI2ODksImV4cCI6MTY2MzU1NDY4OX0.uHDS9-VapXXmqBznUs_39QUCglZxcw5VsRgFUs6WOeE

